tomcat_version: "9.0.107"

java_package: >-
  {% if ansible_distribution == 'Amazon' %}
    java-11-amazon-corretto
  {% elif ansible_os_family == 'Debian' %}
    openjdk-11-jdk
  {% else %}
    java-11-openjdk
  {% endif %}

maven_package: maven
