---
- name: Create custom index page for Debian
  copy:
    dest: /var/www/html/index.html
    content: "<h1>Hello from {{ inventory_hostname }}!</h1>"
  when: ansible_os_family == "Debian"
  tags: configure

- name: Create custom index page for RedHat
  copy:
    dest: /usr/share/nginx/html/index.html
    content: "<h1>Hello from {{ inventory_hostname }}!</h1>"
  when: ansible_os_family == "RedHat"
  tags: configure

- name: Ensure nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: true
  notify: restart nginx
  tags: configure