---
- name: Create custom index page
  copy:
    dest: /var/www/html/index.html
    content: "<h1>Hello from {{ inventory_hostname }}!</h1>"
  tags: configure

- name: Ensure nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: true
  notify: restart nginx
  tags: configure