---
- name: Install Nginx on Debian-based systems
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags: install

- name: Install Nginx on RedHat-based systems
  yum:
    name: nginx
    state: present
  when: ansible_os_family == "RedHat"
  tags: install