---
- name: Install required packages for Docker
  package:
    name:
      - docker
    state: present

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes