---
- name: Include Docker install task for Debian/Ubuntu
  include_tasks: install_debian.yml
  when: ansible_os_family == "Debian"

- name: Include Docker install task for Amazon Linux
  include_tasks: install_amazonlinux.yml
  when: ansible_distribution == "Amazon"

- name: Create directory for custom index.html
  file:
    path: /opt/custom_web
    state: directory
    mode: '0755'

- name: Generate custom index.html from template
  template:
    src: index.html.j2
    dest: /opt/custom_web/index.html

- name: Run nginx container with custom index.html mounted
  community.docker.docker_container:
    name: nginx_demo
    image: nginx:latest
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "8081:80"
    volumes:
      - /opt/custom_web/index.html:/usr/share/nginx/html/index.html:ro
  notify: Restart Docker
