---
- name: Include Docker install task for Debian/Ubuntu
  include_tasks: install_debian.yml
  when: ansible_os_family == "Debian"

- name: Include Docker install task for Amazon Linux
  include_tasks: install_amazonlinux.yml
  when: ansible_distribution == "Amazon"

- name: Run nginx container on a different port to avoid conflict
  community.docker.docker_container:
    name: nginx_demo
    image: nginx:latest
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "8081:80"   # HostPort:ContainerPort
  notify: Restart Docker

- name: Create temporary directory for custom index.html
  file:
    path: /tmp/custom_web
    state: directory
    mode: '0755'

- name: Generate custom index.html from template
  template:
    src: index.html.j2
    dest: /tmp/custom_web/index.html

- name: Copy custom index.html into the running container
  community.docker.docker_cp:
    src: /tmp/custom_web/index.html
    dest: /usr/share/nginx/html/index.html
    container: nginx_demo
