---
- name: Include Docker install task for Debian/Ubuntu
  include_tasks: install_debian.yml
  when: ansible_os_family == "Debian"

- name: Include Docker install task for Amazon Linux
  include_tasks: install_amazonlinux.yml
  when: ansible_distribution == "Amazon"

- name: Run a test container (Nginx)
  docker_container:
    name: nginx_demo
    image: nginx:latest
    state: started
    ports:
      - "8080:80"
  notify: Restart Docker
