---
- name: Install Apache on RedHat-based systems (Amazon Linux)
  yum:
    name: httpd
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install Apache on Debian-based systems (Ubuntu)
  apt:
    name: apache2
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Copy Apache virtual host config (RedHat)
  template:
    src: apache_redhat.conf.j2
    dest: /etc/httpd/conf.d/custom.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'RedHat'
  notify: restart apache

- name: Copy Apache virtual host config (Debian)
  template:
    src: apache_debian.conf.j2
    dest: /etc/apache2/sites-available/custom.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'
  notify: restart apache

- name: Enable site config (Debian)
  file:
    src: /etc/apache2/sites-available/custom.conf
    dest: /etc/apache2/sites-enabled/custom.conf
    state: link
    force: yes
  when: ansible_os_family == 'Debian'
  notify: restart apache

- name: Ensure Apache is started and enabled
  service:
    name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    state: started
    enabled: yes