---
- name: Install Nginx
  package:
    name: nginx
    state: present

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Display webserver port
  debug:
    msg: "Web server is listening on port {{ webserver_port }}"
