---
- name: Add MariaDB YUM repository
  ansible.builtin.yum_repository:
    name: MariaDB
    description: MariaDB Repo
    baseurl: https://yum.mariadb.org/10.5/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes

- name: Install MariaDB server
  ansible.builtin.package:
    name: MariaDB-server
    state: present

- name: Start and enable MariaDB
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes