---
- name: Install MySQL Server on Amazon Linux 2023
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Start and enable MySQL service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true