---
# tasks/install_redhat.yml

- name: Install MySQL server on Amazon Linux 2023
  ansible.builtin.yum:
    name: mysql
    state: present
  when: ansible_facts['distribution'] == 'Amazon' and ansible_facts['distribution_major_version'] == '2023'

- name: Install MariaDB server on other RedHat-based systems
  ansible.builtin.yum:
    name: mariadb-server
    state: present
  when: not (ansible_facts['distribution'] == 'Amazon' and ansible_facts['distribution_major_version'] == '2023')