- name: Install MySQL Server on Amazon Linux 2023
  ansible.builtin.yum:
    name: mysql-server
    state: present
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] == "Amazon"