- name: Full LAMP Setup on Amazon Linux 2023
  hosts: appserver
  become: true

  tasks:
    - name: Install Apache, PHP, MariaDB
      dnf:
        name:
          - httpd
          - php
          - php-mysqlnd
          - mariadb105-server
        state: present

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: true

    - name: Start and enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Install PyMySQL for MySQL modules
      dnf:
        name: python3-PyMySQL
        state: present

    - name: Copy custom index.html to Apache root
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'

    - name: Deploy sample PHP info page
      copy:
        content: "<?php phpinfo(); ?>"
        dest: /var/www/html/info.php
        owner: apache
        group: apache
        mode: '0644'

    - name: Remove test database
      mysql_db:
        name: test
        state: absent

    - name: Remove anonymous users
      mysql_user:
        name: ''
        host_all: yes
        state: absent

    - name: Set root password (optional)
      mysql_user:
        name: root
        host: localhost
        password: "MySecurePassword"
        login_unix_socket: /var/lib/mysql/mysql.sock
        check_implicit_admin: yes