---
- name: Remove LAMP stack from Amazon Linux 2023
  hosts: appserver
  become: true

  tasks:
    - name: Stop and disable Apache
      service:
        name: httpd
        state: stopped
        enabled: false
      ignore_errors: true  # In case it's not installed

    - name: Stop and disable MariaDB
      service:
        name: mariadb
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Remove Apache, MariaDB, PHP packages
      dnf:
        name:
          - httpd
          - mariadb105-server
          - php
        state: absent

    - name: Remove default Apache and PHP files (optional)
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/html/index.html
        - /var/www/html/info.php