- name: Setup LAMP stack
  hosts: appserver
  become: true

  tasks:
    - name: Install packages
      yum:
        name:
          - httpd
          - mariadb-server
          - php
        state: present

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: true