---
- name: Install Python packages and create users
  hosts: appserver
  become: true

  tasks:
    - name: Install Python packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-venv
      loop_control:
        label: "{{ item }}"

    - name: Create users
      user:
        name: "{{ user_name }}"
        state: present
        shell: /bin/bash
      loop:
        - alice
        - bob
        - carol
      loop_control:
        loop_var: user_name