---
- name: Install and configure Nginx on Amazon Linux 2023
  hosts: appserver
  become: true

  tasks:

    - block:
        - name: Stop and disable httpd if running
          service:
            name: httpd
            state: stopped
            enabled: false
          ignore_errors: true
      name: Ensure Apache is not running (if installed)

    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Copy custom index.html (optional)
      copy:
        content: "<h1>Welcome to Nginx on Amazon Linux 2023!</h1>"
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'