---
- name: Fully remove Nginx from Amazon Linux 2023
  hosts: appserver
  become: true

  tasks:
    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped
      ignore_errors: true

    - name: Disable Nginx service
      service:
        name: nginx
        enabled: false
      ignore_errors: true

    - name: Uninstall Nginx package
      dnf:
        name: nginx
        state: absent

    - name: Remove Nginx default web root
      file:
        path: /usr/share/nginx/html
        state: absent
        recurse: true

    - name: Remove Nginx configuration directory
      file:
        path: /etc/nginx
        state: absent
        recurse: true

    - name: Remove Nginx log directory
      file:
        path: /var/log/nginx
        state: absent
        recurse: true

    - name: Remove Nginx systemd service file (optional cleanup)
      file:
        path: /usr/lib/systemd/system/nginx.service
        state: absent
      ignore_errors: true

    - name: Reload systemd daemon (if service file was removed)
      command: systemctl daemon-reload
      when: ansible_facts['os_family'] == "RedHat"