---
- name: Install and configure Nginx with custom index page on Amazon Linux and Ubuntu
  hosts: appserver
  become: true

  vars:
    nginx_index_content: "<h1>Welcome to Nginx from Ansible on {{ ansible_hostname }}!</h1>"
    nginx_index_mode: '0644'

  tasks:
    - name: Set variables for Amazon Linux
      set_fact:
        nginx_owner: nginx
        nginx_group: nginx
        nginx_index_path: /usr/share/nginx/html/index.html
      when: ansible_os_family == "RedHat"

    - name: Set variables for Ubuntu
      set_fact:
        nginx_owner: www-data
        nginx_group: www-data
        nginx_index_path: /var/www/html/index.html
      when: ansible_os_family == "Debian"

    - name: Install Nginx on Amazon Linux
      dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Nginx on Ubuntu
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: true

    - name: Deploy custom index.html
      copy:
        content: "{{ nginx_index_content }}"
        dest: "{{ nginx_index_path }}"
        owner: "{{ nginx_owner }}"
        group: "{{ nginx_group }}"
        mode: "{{ nginx_index_mode }}"
