---
- name: Remove Nginx from Amazon Linux 2023
  hosts: appserver
  become: true

  tasks:

    - name: Stop and disable Nginx service
      service:
        name: nginx
        state: stopped
        enabled: false
      ignore_errors: true  # In case nginx is already removed or not installed

    - name: Uninstall Nginx
      dnf:
        name: nginx
        state: absent

    - name: Remove default Nginx index.html (optional)
      file:
        path: /usr/share/nginx/html/index.html
        state: absent

    - name: Remove entire Nginx web root directory (optional cleanup)
      file:
        path: /usr/share/nginx/html
        state: absent