---
- name: Deploy custom message using group and host variables
  hosts: webservers
  become: true

  tasks:
    - name: Ensure Nginx is installed
      package:
        name: nginx
        state: present

    - name: Create custom index.html
      copy:
        content: |
          <html>
          <body>
            <h1>{{ custom_message }}</h1>
            <p>Running on port {{ nginx_port }}</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Ensure Nginx is started
      service:
        name: nginx
        state: started
        enabled: true