- name: Deploy custom message using group and host variables
  hosts: appserver
  become: true

  tasks:
    - name: Set nginx index path based on OS family
      set_fact:
        nginx_index_path: "{{ '/usr/share/nginx/html/index.html' if ansible_os_family == 'RedHat' else '/var/www/html/index.html' }}"

    - name: Ensure Nginx is installed
      package:
        name: nginx
        state: present

    - name: Create custom index.html
      copy:
        content: |
          <html>
          <body>
            <h1>{{ custom_message }}</h1>
            <p>Running on port {{ nginx_port }}</p>
          </body>
          </html>
        dest: "{{ nginx_index_path }}"
        mode: '0644'

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: true