---
- name: Clone raviLogin repository
  git:
    repo: https://github.com/devopsaws953/raviLogin.git
    dest: /tmp/raviLogin
    force: yes

- name: Build raviLogin WAR using Maven
  command: mvn package
  args:
    chdir: /tmp/raviLogin
  environment:
    MAVEN_OPTS: "-Dmaven.repo.local=/tmp/.m2"

- name: Deploy raviLogin.war to Tomcat
  copy:
    remote_src: yes
    src: /tmp/raviLogin/target/raviLogin.war
    dest: /opt/tomcat/webapps/raviLogin.war
    owner: tomcat
    group: tomcat
    mode: '0644'
  notify: Restart Tomcat

- name: Start Tomcat
  shell: nohup /opt/tomcat/bin/startup.sh &
  args:
    chdir: /opt/tomcat/