---
- name: Create tomcat group
  group:
    name: tomcat
    state: present

- name: Create tomcat user
  user:
    name: tomcat
    shell: /bin/false
    group: tomcat
    create_home: no

- name: Download Tomcat archive
  get_url:
    url: "https://downloads.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: /tmp/apache-tomcat.tar.gz

- name: Extract Tomcat
  unarchive:
    src: /tmp/apache-tomcat.tar.gz
    dest: /opt/
    remote_src: yes
    creates: "/opt/apache-tomcat-{{ tomcat_version }}"

- name: Rename Tomcat directory
  command: mv /opt/apache-tomcat-{{ tomcat_version }} /opt/tomcat
  args:
    creates: /opt/tomcat

- name: Change ownership of Tomcat
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    recurse: yes

- name: Deploy server.xml from template
  template:
    src: server.xml.j2
    dest: /opt/tomcat/conf/server.xml
    owner: tomcat
    group: tomcat
    mode: '0644'
  notify: Restart Tomcat

- name: Copy tomcat-users.xml
  copy:
    src: tomcat-users.xml
    dest: /opt/tomcat/conf/tomcat-users.xml
    owner: tomcat
    group: tomcat
    mode: '0644'