---
- name: Install Apache on Amazon Linux or Ubuntu
  ansible.builtin.package:
    name: "{{ apache_package }}"
    state: present

- name: Ensure Apache is running
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started
    enabled: true

- name: Deploy index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
